dist: trusty
addons:
  chrome: stable
  apt:
    packages: libnss3-tools

language: node_js
node_js:
  - "6"
  - "7"
  - "8"
cache:
  npm: true

before_script:
- mkdir -p $HOME/.pki/nssdb
- certutil -d sql:$HOME/.pki/nssdb -N
- certutil -d sql:$HOME/.pki/nssdb -A -t "P,," -n 'Preact CLI certificate' -i ./lib/resources/cert.pem
- export LIGHTHOUSE_CHROMIUM_PATH=`which google-chrome-stable`
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

script:
- npm run lint
- npm run test
